### ISSUE TITLE
Vyčerpání heap space při podespisování archivu

### ISSUE THREAD

**Issue by PSSGCSim** [Ministerstvo-financi/hazard-komunikacni-rozhrani#3]
Dojde k vyčerpání heap space při pokusu o podepsání souboru. Stroj má v konfiguraci 5 GiB RAM. Při podepisování dostupná paměť klesne na cca 2 GiB. Soubor k podepsání má pouze 145 MiB. Menší soubory se podepisují OK.

```
java -version

java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
```

```
openssl version

OpenSSL 1.0.2k-fips  26 Jan 2017
```

```
java \
        -jar ./crypto_cli-1.0-jar-with-dependencies.jar \
        -f signFile \
        -i "${INPUT_FILE}" \
        -o "${OUTPUT_FILE}" \
        -spks "${PKCS12_FILE}" \
        -pass "${PKCS12_PWD}"

2019-05-07 12:09:30 INFO  DssCommands:88 - Starting signFile
[main] INFO eu.europa.esig.dss.validation.CommonCertificateVerifier - + New CommonCertificateVerifier created.
[main] INFO eu.europa.esig.dss.token.AbstractSignatureTokenConnection - Signature algorithm : SHA256withRSA
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
        at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
        at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:137)
        at org.bouncycastle.asn1.ASN1OutputStream.write(Unknown Source)
        at org.bouncycastle.asn1.ASN1OutputStream.writeTag(Unknown Source)
        at org.bouncycastle.asn1.DERTaggedObject.encode(Unknown Source)
        at org.bouncycastle.asn1.DEROutputStream.writeObject(Unknown Source)
        at org.bouncycastle.asn1.DERSequence.encode(Unknown Source)
        at org.bouncycastle.asn1.DEROutputStream.writeObject(Unknown Source)
        at org.bouncycastle.asn1.DERTaggedObject.encode(Unknown Source)
        at org.bouncycastle.asn1.DEROutputStream.writeObject(Unknown Source)
        at org.bouncycastle.asn1.DERSequence.encode(Unknown Source)
        at org.bouncycastle.asn1.DEROutputStream.writeObject(Unknown Source)
        at eu.europa.esig.dss.cades.signature.CMSSignedDocument.getBytes(CMSSignedDocument.java:76)
        at eu.europa.esig.dss.cades.signature.CMSSignedDocument.openStream(CMSSignedDocument.java:61)
        at eu.europa.esig.dss.CommonDocument.writeTo(CommonDocument.java:59)
        at eu.europa.esig.dss.CommonDocument.save(CommonDocument.java:51)
        at cz.com.spcss.dss.DssSigner.signFile(DssSigner.java:52)
        at com.cgi.spcss.cli.DssCommands.signFile(DssCommands.java:109)
        at com.cgi.spcss.Main.main(Main.java:77)
```

**Comment by MetaCzech** [comment]
Používáte-li výchozí nastavení java, je dostupná pamět relativně malá, můžete pro java nastavit větší pamět přímo v příkazu:
```
java -Xmx5G -Xms1G \
        -jar ./crypto_cli-1.0-jar-with-dependencies.jar \
        -f signFile \
        -i "${INPUT_FILE}" \
        -o "${OUTPUT_FILE}" \
        -spks "${PKCS12_FILE}" \
        -pass "${PKCS12_PWD}"
```
kde příkazem `-Xms1G` nastavíte inicializační (počáteční) paměť na 1 Giga
a příkazem `-Xmx5G` nastavíte maximální pamět na 5 Giga.
S maximální pamětí šetrně - může způsobit pád OS když se to přežene.

Otestováno na Linux prostředí a souboru o velikosti 160 MiB s uvedenými parametry - OK.
Balíček o velikosti 1,2 GiB = `OutOfMemoryError: Java heap space`
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:211)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:167)
        at eu.europa.esig.dss.utils.impl.GoogleGuavaUtils.toByteArray(GoogleGuavaUtils.java:229)
        at eu.europa.esig.dss.utils.Utils.toByteArray(Utils.java:160)
        at eu.europa.esig.dss.DSSUtils.toByteArray(DSSUtils.java:550)
        at eu.europa.esig.dss.DSSUtils.toByteArray(DSSUtils.java:532)
        at eu.europa.esig.dss.cades.signature.CAdESService.getCmsSignedData(CAdESService.java:263)
        at eu.europa.esig.dss.cades.signature.CAdESService.getDataToSign(CAdESService.java:105)
        at eu.europa.esig.dss.cades.signature.CAdESService.getDataToSign(CAdESService.java:64)
        at cz.com.spcss.dss.DssSigner.signFile(DssSigner.java:48)
        at com.cgi.spcss.cli.DssCommands.signFile(DssCommands.java:109)
        at com.cgi.spcss.Main.main(Main.java:77)
```

**Comment by PSSGCSim** [comment]
S tímto nastavením již funguje v pořádku. Děkuji za radu.
